name: unit-testing-learning
on: [push]
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Set up JDK 1.8
    uses: actions/setup-java@v1
    with:
      java-version: 1.8
      - name: Thundra Maven Test Instrumentation
      uses: thundra-io/thundra-maven-test-action@v1
      with:
      apikey: 12ea2270-76ef-4494-9aae-3ced05c4cfe7
      project_id: c57373a9-79b1-4bcd-85bc-9bb267f67495
      command: mvn clean install
